#DIB: appspec.yml v1.0
version: 0.0
os: linux
files:
  - source: /artifacts/
    destination: /opt/magnoliaAuthor/webapps/magnoliaAuthor/WEB-INF/lib/
permissions:
  - object: /opt/magnoliaAuthor/webapps/magnoliaAuthor/WEB-INF/lib/
    pattern: "**"
    owner: tomcat8
    group: tomcat8
    mode: 644
    type:
      - file
  - object: /opt/magnoliaAuthor/webapps/magnoliaAuthor/WEB-INF/lib/
    pattern: "**"
    owner: tomcat8
    group: tomcat8
    mode: 755
    type:
      - directory
hooks:
  BeforeInstall:
    - location: scripts/authorStopServer.sh
      timeout: 300
      runas: root
    - location: scripts/authorBackupAndClean.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/authorStartServer.sh
      timeout: 300
      runas: root
